
spring.cloud.gateway.routes[0].id=Client-MicroService
spring.cloud.gateway.routes[0].uri=${CLIENT_MICROSERVICE_URL_DEV}
spring.cloud.gateway.routes[0].predicates[0]=Path=/Clients/**

spring.cloud.gateway.routes[1].id=Worker-Microservice
spring.cloud.gateway.routes[1].uri=${WORKER_MICROSERVICE_URL_DEV}
spring.cloud.gateway.routes[1].predicates[0]=Path=/workers/**

spring.cloud.gateway.routes[2].id=Workouts-Microservice
spring.cloud.gateway.routes[2].uri=${WORKOUTS_MICROSERVICE_URL_DEV}
spring.cloud.gateway.routes[2].predicates[0]=Path=/Workouts/**

spring.cloud.gateway.routes[3].id=Exercises-Microservice
spring.cloud.gateway.routes[3].uri=${EXERCISES_MICROSERVICE_URL_DEV}
spring.cloud.gateway.routes[3].predicates[0]=Path=/Exercises/**

keycloak.realm=${keycloak.realm}
keycloak.username=${keycloak.username}
keycloak.password=${keycloak.password}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}

cloudinary.cloud-name=${cloudinary_cloud_name}
cloudinary.api-key=${cloudinary_api_key}
cloudinary.api-secret=${cloudinary_api_secret}

cors.allowed-origin=${cors.allowed-origin.dev}

stripe.secret-key=${stripe_secret_key}
stripe.public-key=${stripe_public_key}

keycloak.url=${KEYCLOAK_SERVER_URL}
keycloak.urlApi=${keycloak.url.dev}
cookies.secure=true
spring.security.oauth2.client.provider.keycloak.issuer-uri=${KEYCLOAK_ISSUER_URI}
spring.security.oauth2.client.registration.spring-cloud-gateway-client.client-id=${KEYCLOAK_CLIENT_ID}
spring.security.oauth2.client.registration.spring-cloud-gateway-client.client-secret=${KEYCLOAK_CLIENT_SECRET}
spring.security.oauth2.client.registration.spring-cloud-gateway-client.provider=${KEYCLOAK_PROVIDER}
spring.security.oauth2.client.registration.spring-cloud-gateway-client.authorization-grant-type=${KEYCLOAK_AUTHORIZATION_GRANT_TYPE}
spring.security.oauth2.client.registration.spring-cloud-gateway-client.redirect-uri=${KEYCLOAK_REDIRECT_URI}

spring.main.allow-bean-definition-overriding=true
spring.main.web-application-type=reactive


server.ssl.enabled=true
server.ssl.key-store=${SSL_PATH}
server.ssl.key-store-password=${SSL_PASS}
server.ssl.key-store-type=${SSL_TYPE}
server.ssl.key-alias=${SSL_ALIAS}
