name: CD Pipeline

on:
    workflow_run:
        workflows: ["CI Pipeline"]
        types:
            - completed

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Stop all containers
              run: sudo docker stop $(sudo docker ps -aq)
            - name: Remove all containers
              run: sudo docker rm $(sudo docker ps -aq)
            - name: Remove all Images
              run: sudo docker rmi $(sudo docker images -q)
            - name: Pull Docker image
              run: sudo docker pull alvaroherrero/entrena-sync-apigateway:latest
            - name: Delete Old docker container
              run: sudo docker rm -f entrena-sync-apigateway-container || true
            - name: Run Docker Container
              run: sudo docker run -d --restart always -p 80:80 --name entrena-sync-apigateway-container alvaroherrero/entrena-sync-apigateway

