name: CD Pipeline

on:
    workflow_run:
        workflows: ["CI Pipeline"]
        types:
            - completed

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Pull Docker image
              run: sudo docker pull alvaroherrero/entrena-sync-apigateway:latest
            - name: Delete Old docker container
              run: sudo docker rm -f entrena-sync-apigateway-container || true
            - name: Run Docker Container
              run: sudo docker run -d -p 8080:80 --name entrena-sync-apigateway-container alvaroherrero/entrena-sync-apigateway
